name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: olegtarasov/get-tag@v2.1
      id: tagName
      with:
        tagRegex: "*.*.*"  # Optional. Returns specified group text as tag name.
        tagRegexGroup: 1 # Optional. Default is 1.

    
    - uses: actions/checkout@v3
    - name: Build the Docker image
      with:
        tagname: ${{ steps.tagName.outputs.tag }}
      run:  |
        docker compose -f docker-compose.yml -d --tag lwt:$GIT_TAG_NAME build
        docker run ghcr.io/hugofara/lwt:$GIT_TAG_NAME
        docker push ghcr.io/hugofara/lwt:$GIT_TAG_NAME
        

